#### Sudoku

In [2]:
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,8,9,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,0,8],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]]

In [3]:
print(grid)

[[5, 3, 0, 0, 7, 0, 0, 0, 0], [6, 0, 0, 1, 9, 5, 0, 0, 0], [0, 8, 9, 0, 0, 0, 0, 6, 0], [8, 0, 0, 0, 6, 0, 0, 0, 3], [4, 0, 0, 8, 0, 3, 0, 0, 1], [7, 0, 0, 0, 2, 0, 0, 0, 6], [0, 6, 0, 0, 0, 0, 2, 0, 8], [0, 0, 0, 4, 1, 9, 0, 0, 5], [0, 0, 0, 0, 8, 0, 0, 7, 9]]


In [6]:
!pip install numpy

     --------------------------------------- 14.7/14.7 MB 17.2 MB/s eta 0:00:00


In [7]:
import numpy as np

In [8]:
print(np.matrix(grid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 8 9 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 0 8]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [16]:
# check for position
# check for each square (3x3)

def possible(y,x,n):
    global grid
    for i in range(0,9):
        if grid[y][i] == n:
            return False
    for i in range(0,9):
        if grid[i][x] == n:
            return False
    y0 = (y//3)*3
    x0 = (x//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == n:
                return False
    return True

In [17]:
possible(4,4,3)

False

In [18]:
possible(4,4,5)

True

In [23]:
def solver():
    global grid
    for y in range(0,9):
        for x in range(0,9):
            if grid[y][x] == 0:
                for i in range(1,10):
                    if possible(y,x,i):
                        grid[y][x] = i
                        solver()
                        #backtracking
                        grid[y][x] = 0
                return
    print(np.matrix(grid))
    input("Find another solution:")

In [24]:
solver()

[[5 3 2 6 7 8 1 9 4]
 [6 4 7 1 9 5 3 8 2]
 [1 8 9 3 4 2 5 6 7]
 [8 2 1 7 6 4 9 5 3]
 [4 9 6 8 5 3 7 2 1]
 [7 5 3 9 2 1 8 4 6]
 [9 6 4 5 3 7 2 1 8]
 [2 7 8 4 1 9 6 3 5]
 [3 1 5 2 8 6 4 7 9]]
Find another solution:


In [44]:
grid = [[12,11,23],[23,34,35],[51,55,56]]

In [45]:
print(np.matrix(grid))

[[12 11 23]
 [23 34 35]
 [51 55 56]]


In [32]:
for i in range(0,3):
    for j in range(0,3):
        print(grid[i][j])

12
11
23
23
34
35
51
55
56


In [43]:
for i in range(0,3):
    for j in range(0,3):
        if grid[i][j] == 23:
            print("true", i, j)
        print("not exists", i, j)

not exists 0 0
not exists 0 1
true 0 2
not exists 0 2
true 1 0
not exists 1 0
not exists 1 1
not exists 1 2
not exists 2 0
not exists 2 1
not exists 2 2
